source "https://rubygems.org"

gem "jekyll", "~> 4.3.0"
gem "jekyll-theme-cayman"

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
end

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
gem "csv", "~> 3.3"
gem "logger", "~> 1.7"
gem "base64", "~> 0.3.0"
gem "bigdecimal", "~> 3.3"

gem "minima", "~> 2.5"